
spring:
  application:
    name: UserServiceDemo

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost   # Optional: use if Eureka dashboard shows UNKNOWN host

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
