Spring: 
application:
    name: UserServiceDemo

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost   # Optional, agar IP/hostname UNKNOWN aa raha ho

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

